---
name: Auto Labeler
on:
  # pull_request_target event is required for autolabeler to support all PRs including forks
  pull_request_target:
    types: [opened, reopened, edited, synchronize]
permissions:
  contents: read
jobs:
  main:
    permissions:
      contents: read
      pull-requests: write
    uses: github/ospo-reusable-workflows/.github/workflows/auto-labeler.yaml@9465bed2f569164bd83002542de0800cd4e899b3
    with:
      config-name: release-drafter.yml
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
