---
name: Auto Labeler
on:
  # pull_request_target event is required for autolabeler to support all PRs including forks
  pull_request_target:
    types: [opened, reopened, edited, synchronize]
permissions:
  contents: read
jobs:
  main:
    permissions:
      contents: write
      actions: write
    uses: github/ospo-reusable-workflows/.github/workflows/auto-labeler.yaml@ab23c8c6cb1f6f349025ec549faf83866748863f
    with:
      config-name: release-drafter.yml
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
