## Reference: https://github.com/amannn/action-semantic-pull-request
---
name: "Lint PR Title"
on:
  pull_request_target:
    types: [opened, reopened, edited, synchronize]
permissions:
  contents: read
jobs:
  main:
    permissions:
      contents: read
      pull-requests: read
      statuses: write
    uses: github/ospo-reusable-workflows/.github/workflows/pr-title.yaml@c67026dea966a61bedc1b2fb5f2269ad73ff06cf
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
