---
name: Release
on:
  workflow_dispatch:
  pull_request_target:
    types: [closed]
    branches: [main]
permissions:
  contents: read
jobs:
  release:
    permissions:
      contents: write
      pull-requests: read
    uses: github/ospo-reusable-workflows/.github/workflows/release.yaml@6d41e9f4a53f6273e8f278888d0afeec142761b9
    with:
      publish: true
      release-config-name: release-drafter.yml
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
  release_image:
    needs: release
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    uses: github/ospo-reusable-workflows/.github/workflows/release-image.yaml@6d41e9f4a53f6273e8f278888d0afeec142761b9
    with:
      image-name: ${{ github.repository }}
      full-tag: ${{ needs.release.outputs.full-tag }}
      short-tag: ${{ needs.release.outputs.short-tag }}
      create-attestation: true
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      image-registry: ghcr.io
      image-registry-username: ${{ github.actor }}
      image-registry-password: ${{ secrets.GITHUB_TOKEN }}
